#!/usr/bin/bash
wal -q -i /home/aditya/gitclones//Wallpaper-Bank/wallpapers/Dynamic-Wallpapers/Dark --saturate 1.0 --backend [colorz]

# wal -q -i /home/python/Desktop/test_folder/Wallpaper-Bank/wallpapers/Custom-Wallpapers/brba_wallpaper.png --saturate 1.0 


# wal -q -i /home/python/Desktop/test_folder/Wallpaper-Bank/wallpapers/Dynamic-Wallpapers/Dark/Forest-Dark.png --saturate 0.85 


# The below file is generated by pywal and contains variables for colors and the wallpaper path
source /home/aditya/.cache/wal/colors.sh

# echo "$wallpaper"

# Start hyprpaper for the first time if it is not running
if [[ -z $(ps -e | grep "hyprpaper") ]] then
	hyprpaper -c /home/aditya/.cache/wal/hyprpaper.conf &
fi

hyprpaper unload all
hyprctl hyprpaper preload "$wallpaper"
hyprctl hyprpaper wallpaper ", $wallpaper"

/home/aditya/.config/waybar/scripts/launch.sh & 

killall dunst
dunst -c /home/aditya/.config/dunst/dunstrc &

# Creating copy of wallpaper in .cache for hyprlock

cp "$wallpaper" /home/aditya/.cache/current_background_image

echo "Copied $wallpaper to - $(ls ~/.cache)"

exit 0
